# Generated by Django 5.2.2 on 2025-06-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cartera',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
    ]
