# Generated by Django 5.2.2 on 2025-06-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectDB', '0002_usuario_cartera'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgBid', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(max_length=50)),
                ('direction1', models.CharField(max_length=150)),
                ('direction2', models.CharField(max_length=150)),
                ('timeLimit', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('winner', models.CharField(max_length=50)),
                ('notificated', models.BooleanField(default=False)),
            ],
        ),
    ]
