# Generated by Django 5.2.2 on 2025-06-15 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectDB', '0003_bidformat'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('vehiculo_info', models.JSONField(blank=True, null=True)),
                ('subasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='projectDB.bidformat')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participación en subasta',
                'verbose_name_plural': 'Participaciones en subasta',
                'unique_together': {('usuario', 'subasta')},
            },
        ),
    ]
