# Generated by Django 5.2.2 on 2025-06-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectDB', '0004_bidparticipation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidformat',
            name='winner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
