# Generated by Django 5.2.2 on 2025-06-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectDB', '0005_alter_bidformat_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidformat',
            name='winner',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
