# Generated by Django 5.2.2 on 2025-06-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectDB', '0006_alter_bidformat_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='historial_cartera',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usuario',
            name='historial_subastas_ganadas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='bidparticipation',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
