# Generated by Django 5.2.2 on 2025-06-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectDB', '0007_usuario_historial_cartera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo_recuperacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cartera',
            field=models.IntegerField(default=0.0),
        ),
    ]
