# Generated by Django 5.2.2 on 2025-06-30 15:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectDB', '0008_usuario_codigo_expiracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidformat',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bidformat',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('finalizada', 'Finalizada'), ('exitosa', 'Exitosa'), ('cancelada', 'Cancelada')], default='activa', max_length=20),
        ),
    ]
