# Generated by Django 5.2.2 on 2025-06-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectDB', '0009_bidformat_created_bidformat_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pujas_realizadas',
            field=models.IntegerField(default=0),
        ),
    ]
