# Generated by Django 5.2.2 on 2025-06-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectDB', '0010_usuario_pujas_realizadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pujas_realizadas',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
