# Generated by Django 5.2.2 on 2025-06-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectDB', '0011_alter_usuario_pujas_realizadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='connected',
            field=models.BooleanField(default=True),
        ),
    ]
