# Generated by Django 5.2.2 on 2025-06-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectDB', '0012_usuario_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='participaciones_subastas',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
