# Generated by Django 5.2.2 on 2025-07-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectDB', '0013_usuario_participaciones_subastas'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidformat',
            name='historial_pujas_activa',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
