# Generated by Django 5.2.2 on 2025-07-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectDB', '0014_bidformat_historial_pujas_activa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('body', models.CharField()),
                ('creator', models.CharField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
