# Generated by Django 5.2.2 on 2025-07-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectDB', '0016_userloginrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidformat',
            name='imgBid',
            field=models.ImageField(blank=True, null=True, upload_to='subastas_photos/'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='creator',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='noticias_photos/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='photoPerson',
            field=models.ImageField(blank=True, null=True, upload_to='person_photos/'),
        ),
        migrations.AlterField(
            model_name='vehicleuser',
            name='photoVehicle',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_photos/'),
        ),
    ]
