# Generated by Django 5.2.2 on 2025-07-22 09:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectDB', '0017_alter_bidformat_imgbid_alter_noticias_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidformat',
            name='imgBid',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photoBid'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='portada',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photoNews'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='photoPerson',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photoUser'),
        ),
        migrations.AlterField(
            model_name='vehicleuser',
            name='photoVehicle',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photoVehicle'),
        ),
    ]
