# Generated by Django 5.2.2 on 2025-07-26 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectDB', '0019_fcmtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmtoken',
            name='device_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='fcmtoken',
            unique_together={('user', 'device_id')},
        ),
    ]
