# Generated by Django 5.2.2 on 2025-07-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectDB', '0020_fcmtoken_device_id_alter_fcmtoken_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidformat',
            name='notificado_expiracion',
            field=models.BooleanField(default=False),
        ),
    ]
